### ISSUE TITLE
this code still valid for current versions of Pylint and Pycharm?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [tgamauf/pylint-pycharm#3]

**Comment by kossmak** [comment]
I think yes, my experience of using this package is quite successful.
http://www.evernote.com/l/AANz_IQAHHdIt7e_0ieIMVh2dy2iaitReiw/

**Comment by perses76** [comment]
Hey guys.
I wrote this script many years before and did not expect that somebody uses it.
The logic behind the script is quite simple, so it should work with new version without any problem.
If you need my help me, ping me.
I will try to find time.
Thanks for using it.

**Comment by tgamauf** [comment]
Hi,

I refactored the tool so it is working with Python 2.7, and most current Python 3 versions as well as with the current Pycharm version. Please let me know in a new issue if you run into troubles!
